/*
 * La cave de la Maison Le Nez. Arômes notés de 0 à 5 sur six familles :
 * fromage · animal · fermenté · humide · soufré · écœurant
 */
export const AXES = ['Fromagé', 'Animal', 'Fermenté', 'Humide', 'Soufré', 'Écœurant'];

export const CUVEES = [
  {
    id: 'chaussette', name: 'Chaussette de Randonnée', appel: 'Grand Cru des Sentiers · GR20', year: 2019, liquid: '#8a7a3a', shape: 'bordeaux', label: '#1f2a1c', inten: 5, score: 96,
    aromas: [5, 2, 3, 4, 1, 1],
    robe: 'Jaune paille tirant sur le kaki, reflets de sentier boueux. Légèrement fumante à température ambiante.',
    nez: ['Attaque franche de vieux comté', 'cœur de cuir mouillé et de semelle orthopédique', 'fond persistant de mousse de sous-bois… et de mousse tout court'],
    bouche: 'Nous déconseillons formellement la dégustation en bouche. Un membre du jury s\'y est risqué en 2021.',
    accords: 'Se marie admirablement avec une fenêtre grande ouverte et un sac plastique hermétique.',
    garde: '3 à 5 jours dans un sac de sport fermé. Atteint son apogée au fond d\'un coffre de voiture.',
    expert: '« Une puissance rare. J\'ai pleuré, puis j\'ai déménagé. » — Gaston, nez retraité',
  },
  {
    id: 'frigo', name: 'Frigo d\'Open Space', appel: 'Appellation Bureau Contrôlée · Retour de congés', year: 2024, liquid: '#6f8f5a', shape: 'bourgogne', label: '#20323a', inten: 4, score: 93,
    aromas: [3, 0, 5, 3, 3, 4],
    robe: 'Vert lagune, trouble, avec un dépôt que la science ne sait pas encore nommer.',
    nez: ['Ouverture sur un taboulé de juillet', 'cœur de yaourt « à consommer avant mars »', 'finale complexe de Tupperware sans propriétaire'],
    bouche: 'Personne n\'a osé. Le Tupperware a été jeté avec son contenu, par principe.',
    accords: 'Accompagne un mail passif-agressif « À qui appartient ceci ??? » à toute l\'entreprise.',
    garde: 'Jusqu\'au prochain grand ménage, soit jamais.',
    expert: '« On sent le travail d\'équipe. Chaque collègue a apporté sa pierre. » — Comité d\'entreprise',
  },
  {
    id: 'metro', name: 'Ligne 13, Août, 18 h', appel: 'Cru Urbain · Rames non climatisées', year: 2023, liquid: '#a35b3c', shape: 'flacon', label: '#2a1a14', inten: 5, score: 98,
    aromas: [1, 4, 2, 5, 2, 3],
    robe: 'Ambre orageux, très dense. L\'air y est visiblement épais.',
    nez: ['Attaque de sueur collective', 'cœur de cheveux chauffés au soleil et de sandwich au thon', 'fond métallique de frein et de désespoir'],
    bouche: 'Se respire malgré vous, par la bouche, faute de mieux.',
    accords: 'Une aisselle à hauteur de visage, une poignée de barre poisseuse.',
    garde: 'Se renouvelle chaque jour à 18 h, sans limite.',
    expert: '« Le millésime le plus généreux de la décennie. On en ressort changé. » — Usager quotidien',
  },
  {
    id: 'vestiaire', name: 'Cuvée Mêlée', appel: 'Vestiaire de Rugby · Après match sous la pluie', year: 2022, liquid: '#5e6b4a', shape: 'bordeaux', label: '#1d2433', inten: 5, score: 95,
    aromas: [2, 5, 2, 5, 1, 2],
    robe: 'Kaki profond, opaque, avec une vapeur stagnante au plafond.',
    nez: ['Attaque de crampons boueux', 'cœur de maillots mouillés oubliés dans un sac', 'finale de baume chauffant et de camaraderie'],
    bouche: 'Accompagne la troisième mi-temps, qui en masque partiellement les effets.',
    accords: 'Une pinte tiède, un chant d\'équipe faux.',
    garde: 'Le sac de sport en contient encore des traces depuis 2022.',
    expert: '« Un assemblage de quinze personnalités fortes, et ça se sent. » — L\'arbitre',
  },
  {
    id: 'munster', name: 'Munster en Voiture', appel: 'Grand Cru d\'Été · Plage arrière, 42 °C', year: 2021, liquid: '#c98f3a', shape: 'bourgogne', label: '#3a2412', inten: 5, score: 99,
    aromas: [5, 2, 4, 2, 2, 3],
    robe: 'Or orangé, coulant. Le fromage a littéralement changé d\'état.',
    nez: ['Explosion de croûte lavée', 'cœur d\'étable chauffée au soleil', 'fond de tissu de siège imprégné à vie'],
    bouche: 'Excellent sur une tartine. Le problème n\'est pas le goût, c\'est la voiture.',
    accords: 'Un retour de vacances de 9 heures, vitres fermées, climatisation en panne.',
    garde: 'La voiture a été revendue. L\'acheteur sent encore le millésime.',
    expert: '« Note parfaite. Ma Clio ne s\'en est jamais remise. » — Bernard, Colmar',
  },
  {
    id: 'poubelle', name: 'Poubelle du Dimanche Soir', appel: 'Cuvée Domestique · Ramassage le lundi', year: 2025, liquid: '#4f4a36', shape: 'flacon', label: '#16191c', inten: 4, score: 91,
    aromas: [2, 1, 5, 3, 3, 4],
    robe: 'Brun marécageux, avec des bulles qui remontent toutes seules.',
    nez: ['Attaque d\'épluchures fatiguées', 'cœur de poisson de la veille', 'finale de jus de sac percé sur le parquet'],
    bouche: 'Hors de question.',
    accords: 'Le débat « c\'est ton tour de la descendre » et un couloir étroit.',
    garde: 'Une semaine, si l\'on manque le ramassage. Le voisinage s\'en souvient.',
    expert: '« Rustique, honnête, sans artifice. Un vrai produit du terroir. » — Le voisin du 3e',
  },
  {
    id: 'durian', name: 'Durian Impérial', appel: 'Importation · Interdit dans les transports de Singapour', year: 2020, liquid: '#b7b34a', shape: 'flacon', label: '#24300f', inten: 5, score: 97,
    aromas: [3, 1, 4, 1, 5, 5],
    robe: 'Jaune pâle crémeux, d\'apparence innocente. C\'est un piège.',
    nez: ['Attaque d\'oignon caramélisé', 'cœur de térébenthine et de chaussette', 'finale étonnamment sucrée, presque tropicale'],
    bouche: 'Crémeux et délicieux, paraît-il. Le nez, lui, n\'est pas d\'accord.',
    accords: 'Un hôtel qui l\'interdit explicitement dans le règlement intérieur.',
    garde: 'Se répand dans tout le logement en 4 minutes.',
    expert: '« Le paradis en bouche, l\'enfer au nez. Un grand vin de contraste. » — Voyageur averti',
  },
  {
    id: 'chien', name: 'Réserve Labrador', appel: 'Chien Mouillé · Retour de balade sous la pluie', year: 2023, liquid: '#9a7a52', shape: 'bourgogne', label: '#2e2216', inten: 3, score: 88,
    aromas: [1, 5, 1, 5, 1, 1],
    robe: 'Brun doré, pelage ébouriffé. Secouée, elle éclabousse.',
    nez: ['Attaque de poil humide', 'cœur de flaque et de feuilles mortes', 'finale affectueuse de canapé en velours'],
    bouche: 'Il essaiera de vous faire un bisou. Refusez poliment.',
    accords: 'Un canapé clair, un tapis neuf.',
    garde: 'Jusqu\'au prochain bain, que l\'intéressé refuse.',
    expert: '« Une cuvée qui a du cœur. Et beaucoup de poils. » — Famille Martin',
  },
  {
    id: 'oeuf', name: 'Œuf Dur en TGV', appel: 'Voiture 12 · Paris–Marseille', year: 2024, liquid: '#d8cf9a', shape: 'bordeaux', label: '#2b2d3a', inten: 3, score: 90,
    aromas: [1, 0, 2, 1, 5, 2],
    robe: 'Jaune soufre très pâle. Discrète en apparence, redoutable en milieu clos.',
    nez: ['Attaque soufrée dès l\'écalage', 'cœur de mayonnaise tiède', 'finale de regards accusateurs des voisins de rangée'],
    bouche: 'Correcte, mais servie avec la honte de tout le wagon.',
    accords: 'Un siège côté couloir et 3 h 20 de trajet sans fenêtre ouvrable.',
    garde: 'Jusqu\'à Marseille. Au moins.',
    expert: '« Un classique des familles. Le contrôleur en a parlé au micro. » — Voiture 12',
  },
  {
    id: 'basket', name: 'Air Lycée 2015', appel: 'Basket de Lycéen · Sans chaussettes', year: 2015, liquid: '#7c6a8a', shape: 'flacon', label: '#1d1426', inten: 5, score: 94,
    aromas: [4, 2, 4, 4, 2, 1],
    robe: 'Violet décoloré, avec une semelle visiblement autonome.',
    nez: ['Attaque de caoutchouc chauffé', 'cœur de pied adolescent et de vestiaire de collège', 'finale tenace de déodorant appliqué à la place de la douche'],
    bouche: 'Une odeur si dense qu\'on la mâche presque.',
    accords: 'Une chambre aux volets fermés, une console allumée depuis 14 h.',
    garde: 'Dix ans. Les parents s\'en souviennent encore.',
    expert: '« Le millésime d\'une génération entière. » — Maman de Kévin',
  },
];

/* L'atelier d'assemblage : chaque note a son vocabulaire et sa signature aromatique */
export const NOTES = [
  { id: 'fromage', name: 'Fromage affiné', emo: '🧀', noun: 'Cave', adj: ['crémeuse', 'coulante', 'lactique'], aromas: [5, 1, 3, 1, 1, 1] },
  { id: 'chien', name: 'Chien mouillé', emo: '🐕', noun: 'Chenil', adj: ['velue', 'affectueuse', 'humide'], aromas: [0, 5, 0, 4, 0, 1] },
  { id: 'oeuf', name: 'Œuf pourri', emo: '🥚', noun: 'Soufre', adj: ['sulfurée', 'volcanique', 'implacable'], aromas: [0, 0, 2, 0, 5, 2] },
  { id: 'sueur', name: 'Sueur de vestiaire', emo: '🏉', noun: 'Vestiaire', adj: ['athlétique', 'collective', 'tenace'], aromas: [1, 4, 1, 5, 1, 1] },
  { id: 'lait', name: 'Lait tourné', emo: '🥛', noun: 'Grumeau', adj: ['caillée', 'aigre', 'traîtresse'], aromas: [3, 0, 5, 1, 1, 3] },
  { id: 'poisson', name: 'Poisson de la veille', emo: '🐟', noun: 'Marée', adj: ['iodée', 'marine', 'insistante'], aromas: [0, 2, 3, 3, 3, 3] },
  { id: 'poubelle', name: 'Poubelle chaude', emo: '🗑️', noun: 'Décharge', adj: ['rustique', 'fermentée', 'généreuse'], aromas: [1, 1, 5, 2, 2, 4] },
  { id: 'pied', name: 'Pied d\'athlète', emo: '🦶', noun: 'Semelle', adj: ['caoutchouteuse', 'fromagère', 'confinée'], aromas: [4, 2, 3, 4, 1, 1] },
  { id: 'chou', name: 'Chou bouilli', emo: '🥬', noun: 'Cantine', adj: ['végétale', 'cantinière', 'nostalgique'], aromas: [0, 0, 2, 2, 4, 2] },
  { id: 'durian', name: 'Durian', emo: '🍈', noun: 'Tropique', adj: ['exotique', 'sucrée', 'scandaleuse'], aromas: [2, 0, 3, 0, 4, 5] },
];
